{
 "info": {
  "title": "Twilio - Insights",
  "description": "This is the public Twilio REST API.",
  "termsOfService": "https://www.twilio.com/legal/tos",
  "contact": {
   "name": "Twilio Support",
   "url": "https://support.twilio.com",
   "email": "support@twilio.com"
  },
  "license": {
   "name": "Apache 2.0",
   "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
  },
  "version": "1.0.0"
 },
 "openapi": "3.0.1",
 "servers": [
  {
   "url": "https://insights.twilio.com"
  }
 ],
 "tags": [
  {
   "name": "InsightsV1Annotation"
  },
  {
   "name": "InsightsV1Call"
  },
  {
   "name": "InsightsV1CallSummaries"
  },
  {
   "name": "InsightsV1CallSummary"
  },
  {
   "name": "InsightsV1Conference"
  },
  {
   "name": "InsightsV1ConferenceParticipant"
  },
  {
   "name": "InsightsV1Event"
  },
  {
   "name": "InsightsV1Metric"
  },
  {
   "name": "InsightsV1Participant"
  },
  {
   "name": "InsightsV1Room"
  },
  {
   "name": "InsightsV1Setting"
  }
 ],
 "security": [
  {
   "accountSid_authToken": []
  }
 ],
 "paths": {
  "/v1/Conferences/{ConferenceSid}": {
   "servers": [
    {
     "url": "https://insights.twilio.com"
    }
   ],
   "description": "",
   "x-twilio": {
    "defaultOutputProperties": [
     "conference_sid",
     "account_sid"
    ],
    "dependentProperties": {
     "conference_participants": {
      "mapping": {
       "conference_sid": "conference_sid"
      },
      "resource_url": "/v1/Conferences/{conference_sid}/Participants"
     }
    },
    "pathType": "instance"
   },
   "get": {
    "description": "Get a specific Conference Summary.",
    "summary": "Get a specific Conference Summary.",
    "tags": [
     "InsightsV1Conference"
    ],
    "parameters": [
     {
      "name": "ConferenceSid",
      "in": "path",
      "description": "The unique SID identifier of the Conference.",
      "schema": {
       "type": "string",
       "minLength": 34,
       "maxLength": 34,
       "pattern": "^CF[0-9a-fA-F]{32}$"
      },
      "required": true
     }
    ],
    "responses": {
     "200": {
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/insights.v1.conference"
        },
        "examples": {
         "fetch": {
          "value": {
           "conference_sid": "CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
           "account_sid": "ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
           "friendly_name": "conference1",
           "start_time": "2021-10-08T02:58:51Z",
           "create_time": "2021-10-08T02:58:47Z",
           "end_time": "2021-10-08T03:00:02Z",
           "duration_seconds": 76,
           "connect_duration_seconds": 72,
           "status": "completed",
           "max_participants": 250,
           "max_concurrent_participants": 4,
           "unique_participants": 4,
           "end_reason": "last_participant_left",
           "ended_by": "CAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
           "mixer_region": "us1",
           "mixer_region_requested": "us1",
           "recording_enabled": false,
           "processing_state": "complete",
           "detected_issues": {
            "call_quality": 1,
            "region_configuration": 0,
            "participant_behavior": 3
           },
           "tags": [
            "duplicate_identity",
            "detected_silence",
            "participant_behavior_issues"
           ],
           "tag_info": null,
           "url": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
           "links": {
            "conference_participants": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Participants"
           }
          }
         }
        }
       }
      },
      "headers": {
       "Access-Control-Allow-Origin": {
        "description": "Specify the origin(s) allowed to access the resource",
        "schema": {
         "type": "string"
        },
        "example": "*"
       },
       "Access-Control-Allow-Methods": {
        "description": "Specify the HTTP methods allowed when accessing the resource",
        "schema": {
         "type": "string"
        },
        "example": "POST, OPTIONS"
       },
       "Access-Control-Allow-Headers": {
        "description": "Specify the headers allowed when accessing the resource",
        "schema": {
         "type": "string"
        },
        "example": "Content-Type, Authorization"
       },
       "Access-Control-Allow-Credentials": {
        "description": "Indicates whether the browser should include credentials",
        "schema": {
         "type": "boolean"
        }
       },
       "Access-Control-Expose-Headers": {
        "description": "Headers exposed to the client",
        "schema": {
         "type": "string",
         "example": "X-Custom-Header1, X-Custom-Header2"
        }
       }
      },
      "description": "OK"
     }
    },
    "security": [
     {
      "accountSid_authToken": []
     }
    ],
    "operationId": "FetchConference"
   }
  },
  "/v1/Conferences": {
   "servers": [
    {
     "url": "https://insights.twilio.com"
    }
   ],
   "description": "",
   "x-twilio": {
    "defaultOutputProperties": [
     "conference_sid",
     "account_sid"
    ],
    "dependentProperties": {
     "conference_participants": {
      "mapping": {
       "conference_sid": "conference_sid"
      },
      "resource_url": "/v1/Conferences/{conference_sid}/Participants"
     }
    },
    "pathType": "list"
   },
   "get": {
    "description": "Get a list of Conference Summaries.",
    "summary": "Get a list of Conference Summaries.",
    "tags": [
     "InsightsV1Conference"
    ],
    "parameters": [
     {
      "name": "ConferenceSid",
      "in": "query",
      "description": "The SID of the conference.",
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "FriendlyName",
      "in": "query",
      "description": "Custom label for the conference resource, up to 64 characters.",
      "schema": {
       "type": "string"
      },
      "x-twilio": {
       "pii": {
        "handling": "standard",
        "deleteSla": 30
       }
      },
      "examples": {
       "readWithFriendlynameStartfailure": {
        "value": "outboundConfCallTransferThrice_1"
       }
      }
     },
     {
      "name": "Status",
      "in": "query",
      "description": "Conference status.",
      "schema": {
       "type": "string"
      },
      "examples": {
       "readWithRegion": {
        "value": "completed"
       },
       "readWithFriendlynameStartfailure": {
        "value": "not_started"
       }
      }
     },
     {
      "name": "CreatedAfter",
      "in": "query",
      "description": "Conferences created after the provided timestamp specified in ISO 8601 format",
      "schema": {
       "type": "string"
      },
      "examples": {
       "readFull": {
        "value": "2021-10-09T17:20:53Z"
       }
      }
     },
     {
      "name": "CreatedBefore",
      "in": "query",
      "description": "Conferences created before the provided timestamp specified in ISO 8601 format.",
      "schema": {
       "type": "string"
      },
      "examples": {
       "readFull": {
        "value": "2021-10-12T18:37:53Z"
       }
      }
     },
     {
      "name": "MixerRegion",
      "in": "query",
      "description": "Twilio region where the conference media was mixed.",
      "schema": {
       "type": "string"
      },
      "examples": {
       "readWithRegion": {
        "value": "au1"
       }
      }
     },
     {
      "name": "Tags",
      "in": "query",
      "description": "Tags applied by Twilio for common potential configuration, quality, or performance issues.",
      "schema": {
       "type": "string"
      },
      "examples": {
       "readWithDuplicateIdentity": {
        "value": "duplicate_identity"
       }
      }
     },
     {
      "name": "Subaccount",
      "in": "query",
      "description": "Account SID for the subaccount whose resources you wish to retrieve.",
      "schema": {
       "type": "string",
       "minLength": 34,
       "maxLength": 34,
       "pattern": "^AC[0-9a-fA-F]{32}$"
      }
     },
     {
      "name": "DetectedIssues",
      "in": "query",
      "description": "Potential configuration, behavior, or performance issues detected during the conference.",
      "schema": {
       "type": "string"
      },
      "examples": {
       "readWithDetectedIssueEndreason": {
        "value": "call_quality"
       }
      }
     },
     {
      "name": "EndReason",
      "in": "query",
      "description": "Conference end reason; e.g. last participant left, modified by API, etc.",
      "schema": {
       "type": "string"
      },
      "examples": {
       "readWithDetectedIssueEndreason": {
        "value": "participant_with_end_conference_on_exit_left"
       }
      }
     },
     {
      "name": "PageSize",
      "in": "query",
      "description": "How many resources to return in each list page. The default is 50, and the maximum is 1000.",
      "schema": {
       "type": "integer",
       "format": "int64",
       "minimum": 1,
       "maximum": 1000
      }
     },
     {
      "name": "Page",
      "in": "query",
      "description": "The page index. This value is simply for client state.",
      "schema": {
       "type": "integer",
       "minimum": 0
      }
     },
     {
      "name": "PageToken",
      "in": "query",
      "description": "The page token. This is provided by the API.",
      "schema": {
       "type": "string"
      }
     }
    ],
    "responses": {
     "200": {
      "content": {
       "application/json": {
        "schema": {
         "type": "object",
         "properties": {
          "conferences": {
           "type": "array",
           "items": {
            "$ref": "#/components/schemas/insights.v1.conference"
           }
          },
          "meta": {
           "properties": {
            "first_page_url": {
             "format": "uri",
             "type": "string"
            },
            "key": {
             "type": "string"
            },
            "next_page_url": {
             "format": "uri",
             "nullable": true,
             "type": "string"
            },
            "page": {
             "type": "integer"
            },
            "page_size": {
             "type": "integer"
            },
            "previous_page_url": {
             "format": "uri",
             "nullable": true,
             "type": "string"
            },
            "url": {
             "format": "uri",
             "type": "string"
            }
           },
           "type": "object"
          }
         },
         "title": "ListConferenceResponse"
        },
        "examples": {
         "readFull": {
          "value": {
           "meta": {
            "page": 0,
            "page_size": 25,
            "first_page_url": "https://insights.twilio.com/v1/Conferences?CreatedAfter=2021-10-09T17%3A20%3A53Z&CreatedBefore=2021-10-12T18%3A37%3A53Z&PageSize=25&Page=0",
            "previous_page_url": null,
            "url": "https://insights.twilio.com/v1/Conferences?CreatedAfter=2021-10-09T17%3A20%3A53Z&CreatedBefore=2021-10-12T18%3A37%3A53Z&PageSize=25&Page=0",
            "next_page_url": null,
            "key": "conferences"
           },
           "conferences": [
            {
             "conference_sid": "CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "account_sid": "ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "friendly_name": "conference 1",
             "start_time": "2021-10-12T18:11:10Z",
             "create_time": "2021-10-12T18:11:09Z",
             "end_time": "2021-10-12T18:11:15Z",
             "duration_seconds": 7,
             "connect_duration_seconds": 5,
             "status": "completed",
             "max_participants": 250,
             "max_concurrent_participants": 2,
             "unique_participants": 2,
             "end_reason": "last_participant_left",
             "ended_by": "CAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "mixer_region": "us1",
             "mixer_region_requested": null,
             "recording_enabled": false,
             "processing_state": "complete",
             "detected_issues": {
              "call_quality": 1,
              "region_configuration": 0,
              "participant_behavior": 0
             },
             "tags": null,
             "tag_info": null,
             "url": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "links": {
              "conference_participants": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Participants"
             }
            },
            {
             "conference_sid": "CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab",
             "account_sid": "ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "friendly_name": "conference 2",
             "start_time": null,
             "create_time": "2021-10-12T18:09:21Z",
             "end_time": "2021-10-12T18:09:21Z",
             "duration_seconds": 1,
             "connect_duration_seconds": 0,
             "status": "completed",
             "max_participants": 250,
             "max_concurrent_participants": 2,
             "unique_participants": 3,
             "end_reason": "last_participant_left",
             "ended_by": "CAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab",
             "mixer_region": "us1",
             "mixer_region_requested": null,
             "recording_enabled": false,
             "processing_state": "complete",
             "detected_issues": {
              "call_quality": 1,
              "region_configuration": 0,
              "participant_behavior": 0
             },
             "tags": [
              "detected_silence",
              "participant_behavior_issues"
             ],
             "tag_info": null,
             "url": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab",
             "links": {
              "conference_participants": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab/Participants"
             }
            }
           ]
          }
         },
         "readWithRegion": {
          "value": {
           "meta": {
            "page": 0,
            "page_size": 25,
            "first_page_url": "https://insights.twilio.com/v1/Conferences?MixerRegion=au1&Status=completed&PageSize=25&Page=0",
            "previous_page_url": null,
            "url": "https://insights.twilio.com/v1/Conferences?MixerRegion=au1&Status=completed&PageSize=25&Page=0",
            "next_page_url": null,
            "key": "conferences"
           },
           "conferences": [
            {
             "conference_sid": "CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "account_sid": "ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "friendly_name": "conference 1",
             "start_time": "2021-10-12T18:19:10Z",
             "create_time": "2021-10-12T18:19:09Z",
             "end_time": "2021-10-12T18:20:17Z",
             "duration_seconds": 7,
             "connect_duration_seconds": 5,
             "status": "completed",
             "max_participants": 250,
             "max_concurrent_participants": 2,
             "unique_participants": 2,
             "end_reason": "participant_with_end_conference_on_exit_kicked",
             "ended_by": "CAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "mixer_region": "au1",
             "mixer_region_requested": "au1",
             "recording_enabled": true,
             "processing_state": "complete",
             "detected_issues": {
              "call_quality": 0,
              "region_configuration": 2,
              "participant_behavior": 0
             },
             "tags": [
              "region_configuration_issues"
             ],
             "tag_info": null,
             "url": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "links": {
              "conference_participants": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Participants"
             }
            },
            {
             "conference_sid": "CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab",
             "account_sid": "ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "friendly_name": "conference 2",
             "start_time": "2021-10-12T18:16:53Z",
             "create_time": "2021-10-12T18:16:51Z",
             "end_time": "2021-10-12T18:17:20Z",
             "duration_seconds": 30,
             "connect_duration_seconds": 27,
             "status": "completed",
             "max_participants": 250,
             "max_concurrent_participants": 2,
             "unique_participants": 2,
             "end_reason": "last_participant_left",
             "ended_by": "CAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab",
             "mixer_region": "au1",
             "mixer_region_requested": null,
             "recording_enabled": false,
             "processing_state": "complete",
             "detected_issues": {
              "call_quality": 0,
              "region_configuration": 2,
              "participant_behavior": 3
             },
             "tags": [
              "detected_silence",
              "region_configuration_issues",
              "participant_behavior_issues"
             ],
             "tag_info": null,
             "url": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab",
             "links": {
              "conference_participants": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab/Participants"
             }
            }
           ]
          }
         },
         "readWithFriendlynameStartfailure": {
          "value": {
           "meta": {
            "page": 0,
            "page_size": 25,
            "first_page_url": "https://insights.twilio.com/v1/Conferences?FriendlyName=outboundConfCallTransferThrice_1&Status=not_started&PageSize=25&Page=0",
            "previous_page_url": null,
            "url": "https://insights.twilio.com/v1/Conferences?FriendlyName=outboundConfCallTransferThrice_1&Status=not_started&PageSize=25&Page=0",
            "next_page_url": null,
            "key": "conferences"
           },
           "conferences": [
            {
             "conference_sid": "CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "account_sid": "ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "friendly_name": "outboundConfCallTransferThrice_1",
             "start_time": null,
             "create_time": "2021-11-18T00:09:09Z",
             "end_time": "2021-11-18T00:09:52Z",
             "duration_seconds": 7,
             "connect_duration_seconds": 0,
             "status": "not_started",
             "max_participants": 250,
             "max_concurrent_participants": 1,
             "unique_participants": 1,
             "end_reason": "last_participant_left",
             "ended_by": "CAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "mixer_region": null,
             "mixer_region_requested": null,
             "recording_enabled": false,
             "processing_state": "complete",
             "detected_issues": {
              "call_quality": 0,
              "region_configuration": 0,
              "participant_behavior": 0
             },
             "tags": [
              "participant_behavior_issues",
              "start_failure"
             ],
             "tag_info": {
              "start_failure": {
               "reason": "no_concurrent_participants"
              }
             },
             "url": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "links": {
              "conference_participants": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Participants"
             }
            }
           ]
          }
         },
         "readWithDuplicateIdentity": {
          "value": {
           "meta": {
            "page": 0,
            "page_size": 25,
            "first_page_url": "https://insights.twilio.com/v1/Conferences?Tags=duplicate_identity&PageSize=25&Page=0",
            "previous_page_url": null,
            "url": "https://insights.twilio.com/v1/Conferences?Tags=duplicate_identity&PageSize=25&Page=0",
            "next_page_url": null,
            "key": "conferences"
           },
           "conferences": [
            {
             "conference_sid": "CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "account_sid": "ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "friendly_name": "conference 1",
             "start_time": "2021-11-17T16:21:45Z",
             "create_time": "2021-11-17T16:21:40Z",
             "end_time": "2021-11-17T16:22:11Z",
             "duration_seconds": 32,
             "connect_duration_seconds": 27,
             "status": "not_started",
             "max_participants": 250,
             "max_concurrent_participants": 3,
             "unique_participants": 4,
             "end_reason": "last_participant_left",
             "ended_by": "CAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "mixer_region": "us1",
             "mixer_region_requested": null,
             "recording_enabled": false,
             "processing_state": "complete",
             "detected_issues": {
              "call_quality": 0,
              "region_configuration": 0,
              "participant_behavior": 0
             },
             "tags": [
              "duplicate_identity",
              "detected_silence",
              "participant_behavior_issues"
             ],
             "tag_info": null,
             "url": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "links": {
              "conference_participants": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Participants"
             }
            }
           ]
          }
         },
         "readWithDetectedIssueEndreason": {
          "value": {
           "meta": {
            "page": 0,
            "page_size": 25,
            "first_page_url": "https://insights.twilio.com/v1/Conferences?DetectedIssues=call_quality&EndReason=participant_with_end_conference_on_exit_left&PageSize=25&Page=0",
            "previous_page_url": null,
            "url": "https://insights.twilio.com/v1/Conferences?DetectedIssues=call_quality&EndReason=participant_with_end_conference_on_exit_left&PageSize=25&Page=0",
            "next_page_url": null,
            "key": "conferences"
           },
           "conferences": [
            {
             "conference_sid": "CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "account_sid": "ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "friendly_name": "conference 1",
             "start_time": "2021-11-17T16:21:45Z",
             "create_time": "2021-11-17T16:21:40Z",
             "end_time": "2021-11-17T16:22:11Z",
             "duration_seconds": 32,
             "connect_duration_seconds": 27,
             "status": "not_started",
             "max_participants": 250,
             "max_concurrent_participants": 3,
             "unique_participants": 3,
             "end_reason": "participant_with_end_conference_on_exit_left",
             "ended_by": "CAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "mixer_region": "us1",
             "mixer_region_requested": null,
             "recording_enabled": false,
             "processing_state": "complete",
             "detected_issues": {
              "call_quality": 3,
              "region_configuration": 0,
              "participant_behavior": 1
             },
             "tags": [
              "high_packet_loss",
              "low_mos",
              "participant_behavior_issues",
              "quality_warnings",
              "high_jitter",
              "detected_silence"
             ],
             "tag_info": null,
             "url": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "links": {
              "conference_participants": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Participants"
             }
            }
           ]
          }
         }
        }
       }
      },
      "headers": {
       "Access-Control-Allow-Origin": {
        "description": "Specify the origin(s) allowed to access the resource",
        "schema": {
         "type": "string"
        },
        "example": "*"
       },
       "Access-Control-Allow-Methods": {
        "description": "Specify the HTTP methods allowed when accessing the resource",
        "schema": {
         "type": "string"
        },
        "example": "POST, OPTIONS"
       },
       "Access-Control-Allow-Headers": {
        "description": "Specify the headers allowed when accessing the resource",
        "schema": {
         "type": "string"
        },
        "example": "Content-Type, Authorization"
       },
       "Access-Control-Allow-Credentials": {
        "description": "Indicates whether the browser should include credentials",
        "schema": {
         "type": "boolean"
        }
       },
       "Access-Control-Expose-Headers": {
        "description": "Headers exposed to the client",
        "schema": {
         "type": "string",
         "example": "X-Custom-Header1, X-Custom-Header2"
        }
       }
      },
      "description": "OK"
     }
    },
    "security": [
     {
      "accountSid_authToken": []
     }
    ],
    "operationId": "ListConference"
   }
  },
  "/v1/Conferences/{ConferenceSid}/Participants/{ParticipantSid}": {
   "servers": [
    {
     "url": "https://insights.twilio.com"
    }
   ],
   "description": "",
   "x-twilio": {
    "defaultOutputProperties": [
     "participant_sid",
     "conference_sid",
     "call_sid",
     "account_sid"
    ],
    "parent": "/Conferences/{ConferenceSid}",
    "mountName": "conference_participants",
    "pathType": "instance"
   },
   "get": {
    "description": "Get a specific Conference Participant Summary for a Conference.",
    "summary": "Get a specific Conference Participant Summary for a Conference.",
    "tags": [
     "InsightsV1ConferenceParticipant"
    ],
    "parameters": [
     {
      "name": "ConferenceSid",
      "in": "path",
      "description": "The unique SID identifier of the Conference.",
      "schema": {
       "type": "string",
       "minLength": 34,
       "maxLength": 34,
       "pattern": "^CF[0-9a-fA-F]{32}$"
      },
      "required": true
     },
     {
      "name": "ParticipantSid",
      "in": "path",
      "description": "The unique SID identifier of the Participant.",
      "schema": {
       "type": "string",
       "minLength": 34,
       "maxLength": 34,
       "pattern": "^CP[0-9a-fA-F]{32}$"
      },
      "required": true
     },
     {
      "name": "Events",
      "in": "query",
      "description": "Conference events generated by application or participant activity; e.g. `hold`, `mute`, etc.",
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "Metrics",
      "in": "query",
      "description": "Object. Contains participant call quality metrics.",
      "schema": {
       "type": "string"
      }
     }
    ],
    "responses": {
     "200": {
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/insights.v1.conference.conference_participant"
        },
        "examples": {
         "fetch": {
          "value": {
           "participant_sid": "CPaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
           "label": null,
           "conference_sid": "CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
           "call_sid": "CAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
           "account_sid": "ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
           "call_direction": "outbound",
           "from": "+10000000000",
           "to": "+1000000001",
           "call_status": "completed",
           "country_code": "US",
           "is_moderator": true,
           "join_time": "2021-10-08T02:58:59Z",
           "leave_time": "2021-10-08T03:00:02Z",
           "duration_seconds": 64,
           "outbound_queue_length": 0,
           "outbound_time_in_queue": 965,
           "jitter_buffer_size": null,
           "is_coach": false,
           "coached_participants": null,
           "participant_region": "us1",
           "conference_region": "us1",
           "call_type": "carrier",
           "processing_state": "complete",
           "properties": {
            "start_conference_on_enter": false,
            "end_conference_on_exit": false,
            "play_early_media": false,
            "enter_muted": true,
            "beep_on_enter": false,
            "beep_on_exit": false
           },
           "events": {
            "mute": [
             1633705131000
            ]
           },
           "metrics": {
            "inbound": {
             "total_packets_lost": 0,
             "total_packets_received": 49,
             "packet_loss_percentage": 0.0,
             "jitter": {
              "avg": 0.34,
              "max": 0.53
             },
             "latency": {
              "avg": 0.0,
              "max": 0.0
             },
             "mos": 4.4
            },
            "outbound": {
             "total_packets_lost": 0,
             "total_packets_received": 126,
             "packet_loss_percentage": 0,
             "jitter": {
              "avg": 0.01,
              "max": 0.01
             },
             "latency": {
              "avg": 0,
              "max": 0
             },
             "mos": 4.4
            }
           },
           "url": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Participants/CPaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
          }
         }
        }
       }
      },
      "headers": {
       "Access-Control-Allow-Origin": {
        "description": "Specify the origin(s) allowed to access the resource",
        "schema": {
         "type": "string"
        },
        "example": "*"
       },
       "Access-Control-Allow-Methods": {
        "description": "Specify the HTTP methods allowed when accessing the resource",
        "schema": {
         "type": "string"
        },
        "example": "POST, OPTIONS"
       },
       "Access-Control-Allow-Headers": {
        "description": "Specify the headers allowed when accessing the resource",
        "schema": {
         "type": "string"
        },
        "example": "Content-Type, Authorization"
       },
       "Access-Control-Allow-Credentials": {
        "description": "Indicates whether the browser should include credentials",
        "schema": {
         "type": "boolean"
        }
       },
       "Access-Control-Expose-Headers": {
        "description": "Headers exposed to the client",
        "schema": {
         "type": "string",
         "example": "X-Custom-Header1, X-Custom-Header2"
        }
       }
      },
      "description": "OK"
     }
    },
    "security": [
     {
      "accountSid_authToken": []
     }
    ],
    "operationId": "FetchConferenceParticipant"
   }
  },
  "/v1/Conferences/{ConferenceSid}/Participants": {
   "servers": [
    {
     "url": "https://insights.twilio.com"
    }
   ],
   "description": "",
   "x-twilio": {
    "defaultOutputProperties": [
     "participant_sid",
     "conference_sid",
     "call_sid",
     "account_sid"
    ],
    "parent": "/Conferences/{ConferenceSid}",
    "mountName": "conference_participants",
    "pathType": "list"
   },
   "get": {
    "description": "Get a list of Conference Participants Summaries for a Conference.",
    "summary": "Get a list of Conference Participants Summaries for a Conference.",
    "tags": [
     "InsightsV1ConferenceParticipant"
    ],
    "parameters": [
     {
      "name": "ConferenceSid",
      "in": "path",
      "description": "The unique SID identifier of the Conference.",
      "schema": {
       "type": "string",
       "minLength": 34,
       "maxLength": 34,
       "pattern": "^CF[0-9a-fA-F]{32}$"
      },
      "required": true
     },
     {
      "name": "ParticipantSid",
      "in": "query",
      "description": "The unique SID identifier of the Participant.",
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "Label",
      "in": "query",
      "description": "User-specified label for a participant.",
      "schema": {
       "type": "string"
      },
      "x-twilio": {
       "pii": {
        "handling": "standard",
        "deleteSla": 30
       }
      },
      "examples": {
       "readWithLabel": {
        "value": "client"
       }
      }
     },
     {
      "name": "Events",
      "in": "query",
      "description": "Conference events generated by application or participant activity; e.g. `hold`, `mute`, etc.",
      "schema": {
       "type": "string"
      }
     },
     {
      "name": "PageSize",
      "in": "query",
      "description": "How many resources to return in each list page. The default is 50, and the maximum is 1000.",
      "schema": {
       "type": "integer",
       "format": "int64",
       "minimum": 1,
       "maximum": 1000
      }
     },
     {
      "name": "Page",
      "in": "query",
      "description": "The page index. This value is simply for client state.",
      "schema": {
       "type": "integer",
       "minimum": 0
      }
     },
     {
      "name": "PageToken",
      "in": "query",
      "description": "The page token. This is provided by the API.",
      "schema": {
       "type": "string"
      }
     }
    ],
    "responses": {
     "200": {
      "content": {
       "application/json": {
        "schema": {
         "type": "object",
         "properties": {
          "participants": {
           "type": "array",
           "items": {
            "$ref": "#/components/schemas/insights.v1.conference.conference_participant"
           }
          },
          "meta": {
           "properties": {
            "first_page_url": {
             "format": "uri",
             "type": "string"
            },
            "key": {
             "type": "string"
            },
            "next_page_url": {
             "format": "uri",
             "nullable": true,
             "type": "string"
            },
            "page": {
             "type": "integer"
            },
            "page_size": {
             "type": "integer"
            },
            "previous_page_url": {
             "format": "uri",
             "nullable": true,
             "type": "string"
            },
            "url": {
             "format": "uri",
             "type": "string"
            }
           },
           "type": "object"
          }
         },
         "title": "ListConferenceParticipantResponse"
        },
        "examples": {
         "readFull": {
          "value": {
           "meta": {
            "page": 0,
            "page_size": 25,
            "first_page_url": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Participants?PageSize=25&Page=0",
            "previous_page_url": null,
            "url": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Participants?PageSize=25&Page=0",
            "next_page_url": null,
            "key": "participants"
           },
           "participants": [
            {
             "participant_sid": "CPaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "label": null,
             "conference_sid": "CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "call_sid": "CAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "account_sid": "ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "call_direction": "outbound",
             "from": "+10000000000",
             "to": "+10000000001",
             "call_status": "completed",
             "country_code": "US",
             "is_moderator": true,
             "join_time": "2021-10-08T02:58:51Z",
             "leave_time": "2021-10-08T02:59:55Z",
             "duration_seconds": 65,
             "outbound_queue_length": 0,
             "outbound_time_in_queue": 3361,
             "jitter_buffer_size": null,
             "is_coach": false,
             "coached_participants": null,
             "participant_region": "us1",
             "conference_region": "us1",
             "call_type": "carrier",
             "processing_state": "complete",
             "properties": {
              "start_conference_on_enter": true,
              "end_conference_on_exit": false,
              "play_early_media": true,
              "enter_muted": false,
              "beep_on_enter": false,
              "beep_on_exit": false
             },
             "metrics": {
              "inbound": {
               "total_packets_lost": 0,
               "total_packets_received": 70,
               "packet_loss_percentage": 0.0,
               "jitter": {
                "avg": 0.41,
                "max": 0.84
               },
               "latency": {
                "avg": 0.0,
                "max": 0.0
               },
               "mos": 4.4
              },
              "outbound": {
               "total_packets_lost": 0,
               "total_packets_received": 126,
               "packet_loss_percentage": 0,
               "jitter": {
                "avg": 0.01,
                "max": 0.01
               },
               "latency": {
                "avg": 0,
                "max": 0
               },
               "mos": 4.4
              }
             },
             "events": null,
             "url": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Participants/CPaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
            },
            {
             "participant_sid": "CPaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab",
             "label": null,
             "conference_sid": "CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "call_sid": "CAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab",
             "account_sid": "ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "call_direction": "outbound",
             "from": "+10000000000",
             "to": "+10000000002",
             "call_status": "completed",
             "country_code": "US",
             "is_moderator": true,
             "join_time": "2021-10-08T02:58:52Z",
             "leave_time": "2021-10-08T02:59:54Z",
             "duration_seconds": 63,
             "outbound_queue_length": 0,
             "outbound_time_in_queue": 321,
             "jitter_buffer_size": null,
             "is_coach": false,
             "coached_participants": null,
             "participant_region": "us1",
             "conference_region": "us1",
             "call_type": "carrier",
             "processing_state": "complete",
             "properties": {
              "start_conference_on_enter": false,
              "end_conference_on_exit": false,
              "early_media": false,
              "enter_muted": true,
              "beep_on_enter": false,
              "beep_on_exit": false
             },
             "metrics": {
              "inbound": {
               "total_packets_lost": 0,
               "total_packets_received": 16,
               "packet_loss_percentage": 0,
               "jitter": {
                "avg": 0.26,
                "max": 0.45
               },
               "latency": {
                "avg": 0,
                "max": 0
               },
               "mos": 4.4
              },
              "outbound": {
               "total_packets_lost": 0,
               "total_packets_received": 42,
               "packet_loss_percentage": 0,
               "jitter": {
                "avg": 0.03,
                "max": 0.08
               },
               "latency": {
                "avg": 0,
                "max": 0
               },
               "mos": 4.4,
               "tags": [
                "silent"
               ]
              }
             },
             "events": {
              "mute": [
               1633705131000
              ]
             },
             "url": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Participants/CPaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab"
            }
           ]
          }
         },
         "readWithLabel": {
          "value": {
           "meta": {
            "page": 0,
            "page_size": 25,
            "first_page_url": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Participants?Label=client&PageSize=25&Page=0",
            "previous_page_url": null,
            "url": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Participants?Label=client&PageSize=25&Page=0",
            "next_page_url": null,
            "key": "participants"
           },
           "participants": [
            {
             "participant_sid": "CPaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "conference_sid": "CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "call_sid": "CAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "account_sid": "ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
             "call_direction": "outbound",
             "from": "+10000000000",
             "to": "+10000000001",
             "call_status": "completed",
             "country_code": "US",
             "is_moderator": true,
             "join_time": "2021-10-08T02:58:51Z",
             "leave_time": "2021-10-08T02:59:55Z",
             "duration_seconds": 65,
             "label": "client",
             "outbound_queue_length": 0,
             "outbound_time_in_queue": 3361,
             "jitter_buffer_size": null,
             "is_coach": false,
             "coached_participants": null,
             "participant_region": "us1",
             "conference_region": "us1",
             "call_type": "carrier",
             "processing_state": "complete",
             "properties": {
              "start_conference_on_enter": true,
              "end_conference_on_exit": false,
              "play_early_media": true,
              "enter_muted": false,
              "beep_on_enter": false,
              "beep_on_exit": false
             },
             "metrics": {
              "inbound": {
               "total_packets_lost": 0,
               "total_packets_received": 70,
               "packet_loss_percentage": 0.0,
               "jitter": {
                "avg": 0.41,
                "max": 0.84
               },
               "latency": {
                "avg": 0.0,
                "max": 0.0
               },
               "mos": 4.4
              },
              "outbound": {
               "total_packets_lost": 0,
               "total_packets_received": 96,
               "packet_loss_percentage": 0,
               "jitter": {
                "avg": 0.01,
                "max": 0.01
               },
               "latency": {
                "avg": 0,
                "max": 0
               },
               "mos": 4.4
              }
             },
             "events": null,
             "url": "https://insights.twilio.com/v1/Conferences/CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/Participants/CPaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
            }
           ]
          }
         }
        }
       }
      },
      "headers": {
       "Access-Control-Allow-Origin": {
        "description": "Specify the origin(s) allowed to access the resource",
        "schema": {
         "type": "string"
        },
        "example": "*"
       },
       "Access-Control-Allow-Methods": {
        "description": "Specify the HTTP methods allowed when accessing the resource",
        "schema": {
         "type": "string"
        },
        "example": "POST, OPTIONS"
       },
       "Access-Control-Allow-Headers": {
        "description": "Specify the headers allowed when accessing the resource",
        "schema": {
         "type": "string"
        },
        "example": "Content-Type, Authorization"
       },
       "Access-Control-Allow-Credentials": {
        "description": "Indicates whether the browser should include credentials",
        "schema": {
         "type": "boolean"
        }
       },
       "Access-Control-Expose-Headers": {
        "description": "Headers exposed to the client",
        "schema": {
         "type": "string",
         "example": "X-Custom-Header1, X-Custom-Header2"
        }
       }
      },
      "description": "OK"
     }
    },
    "security": [
     {
      "accountSid_authToken": []
     }
    ],
    "operationId": "ListConferenceParticipant"
   }
  }
 },
 "components": {
  "schemas": {
   "conference_enum_conference_end_reason": {
    "type": "string",
    "enum": [
     "last_participant_left",
     "conference_ended_via_api",
     "participant_with_end_conference_on_exit_left",
     "last_participant_kicked",
     "participant_with_end_conference_on_exit_kicked"
    ]
   },
   "conference_enum_conference_status": {
    "type": "string",
    "enum": [
     "in_progress",
     "not_started",
     "completed",
     "summary_timeout"
    ]
   },
   "conference_enum_processing_state": {
    "type": "string",
    "enum": [
     "complete",
     "in_progress",
     "timeout"
    ]
   },
   "conference_enum_region": {
    "type": "string",
    "enum": [
     "us1",
     "us2",
     "au1",
     "br1",
     "ie1",
     "jp1",
     "sg1",
     "de1",
     "in1"
    ]
   },
   "conference_enum_tag": {
    "type": "string",
    "enum": [
     "invalid_requested_region",
     "duplicate_identity",
     "start_failure",
     "region_configuration_issues",
     "quality_warnings",
     "participant_behavior_issues",
     "high_packet_loss",
     "high_jitter",
     "high_latency",
     "low_mos",
     "detected_silence",
     "no_concurrent_participants"
    ]
   },
   "conference_participant_enum_call_direction": {
    "type": "string",
    "enum": [
     "inbound",
     "outbound"
    ]
   },
   "conference_participant_enum_call_status": {
    "type": "string",
    "enum": [
     "answered",
     "completed",
     "busy",
     "fail",
     "noanswer",
     "ringing",
     "canceled"
    ]
   },
   "conference_participant_enum_call_type": {
    "type": "string",
    "enum": [
     "carrier",
     "client",
     "sip"
    ]
   },
   "conference_participant_enum_jitter_buffer_size": {
    "type": "string",
    "enum": [
     "large",
     "small",
     "medium",
     "off"
    ]
   },
   "conference_participant_enum_processing_state": {
    "type": "string",
    "enum": [
     "complete",
     "in_progress",
     "timeout"
    ]
   },
   "conference_participant_enum_region": {
    "type": "string",
    "enum": [
     "us1",
     "us2",
     "au1",
     "br1",
     "ie1",
     "jp1",
     "sg1",
     "de1",
     "in1"
    ]
   },
   "insights.v1.conference": {
    "type": "object",
    "properties": {
     "conference_sid": {
      "type": "string",
      "minLength": 34,
      "maxLength": 34,
      "pattern": "^CF[0-9a-fA-F]{32}$",
      "nullable": true,
      "description": "The unique SID identifier of the Conference."
     },
     "account_sid": {
      "type": "string",
      "minLength": 34,
      "maxLength": 34,
      "pattern": "^AC[0-9a-fA-F]{32}$",
      "nullable": true,
      "description": "The unique SID identifier of the Account."
     },
     "friendly_name": {
      "type": "string",
      "nullable": true,
      "description": "Custom label for the conference resource, up to 64 characters.",
      "x-twilio": {
       "pii": {
        "handling": "standard",
        "deleteSla": 30
       }
      }
     },
     "create_time": {
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Conference creation date and time in ISO 8601 format."
     },
     "start_time": {
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Timestamp in ISO 8601 format when the conference started. Conferences do not start until at least two participants join, at least one of whom has startConferenceOnEnter=true."
     },
     "end_time": {
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "Conference end date and time in ISO 8601 format."
     },
     "duration_seconds": {
      "type": "integer",
      "nullable": true,
      "description": "Conference duration in seconds."
     },
     "connect_duration_seconds": {
      "type": "integer",
      "nullable": true,
      "description": "Duration of the between conference start event and conference end event in seconds."
     },
     "status": {
      "type": "string",
      "$ref": "#/components/schemas/conference_enum_conference_status",
      "nullable": true,
      "description": "Status of this Conference; `in_progress`, `not_started`, `completed` or `summary_timeout`. if Twilio don't receive `last_participant_left` event, summary will be timeout after 24 hours"
     },
     "max_participants": {
      "type": "integer",
      "nullable": true,
      "description": "Maximum number of concurrent participants as specified by the configuration."
     },
     "max_concurrent_participants": {
      "type": "integer",
      "nullable": true,
      "description": "Actual maximum number of concurrent participants in the conference."
     },
     "unique_participants": {
      "type": "integer",
      "nullable": true,
      "description": "Unique conference participants based on caller ID."
     },
     "end_reason": {
      "type": "string",
      "$ref": "#/components/schemas/conference_enum_conference_end_reason",
      "nullable": true,
      "description": "Conference end reason; e.g. last participant left, modified by API, etc."
     },
     "ended_by": {
      "type": "string",
      "minLength": 34,
      "maxLength": 34,
      "pattern": "^CA[0-9a-fA-F]{32}$",
      "nullable": true,
      "description": "Call SID of the participant whose actions ended the conference."
     },
     "mixer_region": {
      "type": "string",
      "$ref": "#/components/schemas/conference_enum_region",
      "nullable": true,
      "description": "Twilio region where the conference media was mixed."
     },
     "mixer_region_requested": {
      "type": "string",
      "$ref": "#/components/schemas/conference_enum_region",
      "nullable": true,
      "description": "Twilio region where conference mixed was specified to be mixed in configuration."
     },
     "recording_enabled": {
      "type": "boolean",
      "nullable": true,
      "description": "Boolean. Indicates whether recording was enabled at the conference mixer."
     },
     "detected_issues": {
      "type": "object",
      "nullable": true,
      "description": "Potential issues detected by Twilio during the conference."
     },
     "tags": {
      "type": "array",
      "items": {
       "type": "string",
       "$ref": "#/components/schemas/conference_enum_tag"
      },
      "nullable": true,
      "description": "Tags for detected conference conditions and participant behaviors which may be of interest."
     },
     "tag_info": {
      "type": "object",
      "nullable": true,
      "description": "Object. Contains details about conference tags including severity."
     },
     "processing_state": {
      "type": "string",
      "$ref": "#/components/schemas/conference_enum_processing_state",
      "nullable": true,
      "description": "Processing state for the Conference Summary resource. Will be `in_progress` while data is being aggregated, `timeout` if Twilio couldn't process the summary in 24hrs, and `complete` once aggregations and analysis has ended."
     },
     "url": {
      "type": "string",
      "format": "uri",
      "nullable": true,
      "description": "The URL of this resource."
     },
     "links": {
      "type": "object",
      "format": "uri-map",
      "nullable": true,
      "description": "Contains a dictionary of URL links to nested resources of this Conference."
     }
    }
   },
   "insights.v1.conference.conference_participant": {
    "type": "object",
    "properties": {
     "participant_sid": {
      "type": "string",
      "minLength": 34,
      "maxLength": 34,
      "pattern": "^CP[0-9a-fA-F]{32}$",
      "nullable": true,
      "description": "SID for this participant."
     },
     "label": {
      "type": "string",
      "nullable": true,
      "description": "The user-specified label of this participant.",
      "x-twilio": {
       "pii": {
        "handling": "standard",
        "deleteSla": 30
       }
      }
     },
     "conference_sid": {
      "type": "string",
      "minLength": 34,
      "maxLength": 34,
      "pattern": "^CF[0-9a-fA-F]{32}$",
      "nullable": true,
      "description": "The unique SID identifier of the Conference."
     },
     "call_sid": {
      "type": "string",
      "minLength": 34,
      "maxLength": 34,
      "pattern": "^CA[0-9a-fA-F]{32}$",
      "nullable": true,
      "description": "Unique SID identifier of the call that generated the Participant resource."
     },
     "account_sid": {
      "type": "string",
      "minLength": 34,
      "maxLength": 34,
      "pattern": "^AC[0-9a-fA-F]{32}$",
      "nullable": true,
      "description": "The unique SID identifier of the Account."
     },
     "call_direction": {
      "type": "string",
      "$ref": "#/components/schemas/conference_participant_enum_call_direction",
      "nullable": true,
      "description": "Call direction of the participant; inbound or outbound."
     },
     "from": {
      "type": "string",
      "nullable": true,
      "description": "Caller ID of the calling party.",
      "x-twilio": {
       "pii": {
        "handling": "standard",
        "deleteSla": 30
       }
      }
     },
     "to": {
      "type": "string",
      "nullable": true,
      "description": "Called party.",
      "x-twilio": {
       "pii": {
        "handling": "standard",
        "deleteSla": 30
       }
      }
     },
     "call_status": {
      "type": "string",
      "$ref": "#/components/schemas/conference_participant_enum_call_status",
      "nullable": true,
      "description": "Call status of the call that generated the participant."
     },
     "country_code": {
      "type": "string",
      "nullable": true,
      "description": "ISO alpha-2 country code of the participant based on caller ID or called number."
     },
     "is_moderator": {
      "type": "boolean",
      "nullable": true,
      "description": "Boolean. Indicates whether participant had startConferenceOnEnter=true or endConferenceOnExit=true."
     },
     "join_time": {
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "ISO 8601 timestamp of participant join event."
     },
     "leave_time": {
      "type": "string",
      "format": "date-time",
      "nullable": true,
      "description": "ISO 8601 timestamp of participant leave event."
     },
     "duration_seconds": {
      "type": "integer",
      "nullable": true,
      "description": "Participant durations in seconds."
     },
     "outbound_queue_length": {
      "type": "integer",
      "nullable": true,
      "description": "Add Participant API only. Estimated time in queue at call creation."
     },
     "outbound_time_in_queue": {
      "type": "integer",
      "nullable": true,
      "description": "Add Participant API only. Actual time in queue in seconds."
     },
     "jitter_buffer_size": {
      "type": "string",
      "$ref": "#/components/schemas/conference_participant_enum_jitter_buffer_size",
      "nullable": true,
      "description": "The Jitter Buffer Size of this Conference Participant. One of `large`, `small`, `medium` or `off`."
     },
     "is_coach": {
      "type": "boolean",
      "nullable": true,
      "description": "Boolean. Indicated whether participant was a coach."
     },
     "coached_participants": {
      "type": "array",
      "items": {
       "type": "string"
      },
      "nullable": true,
      "description": "Call SIDs coached by this participant."
     },
     "participant_region": {
      "type": "string",
      "$ref": "#/components/schemas/conference_participant_enum_region",
      "nullable": true,
      "description": "Twilio region where the participant media originates."
     },
     "conference_region": {
      "type": "string",
      "$ref": "#/components/schemas/conference_participant_enum_region",
      "nullable": true,
      "description": "The Conference Region of this Conference Participant. One of `us1`, `us2`, `au1`, `br1`, `ie1`, `jp1`, `sg1` or `de1`."
     },
     "call_type": {
      "type": "string",
      "$ref": "#/components/schemas/conference_participant_enum_call_type",
      "nullable": true,
      "description": "The Call Type of this Conference Participant. One of `carrier`, `client` or `sip`."
     },
     "processing_state": {
      "type": "string",
      "$ref": "#/components/schemas/conference_participant_enum_processing_state",
      "nullable": true,
      "description": "Processing state of the Participant Summary. Will be `in_progress` while data is being aggregated, `timeout` if Twilio couldn't process the summary in 24hrs, and `complete` once aggregations and analysis has ended."
     },
     "properties": {
      "type": "object",
      "nullable": true,
      "description": "Participant properties and metadata."
     },
     "events": {
      "type": "object",
      "nullable": true,
      "description": "Object containing information of actions taken by participants. Contains a dictionary of URL links to nested resources of this Conference Participant."
     },
     "metrics": {
      "type": "object",
      "nullable": true,
      "description": "Object. Contains participant call quality metrics."
     },
     "url": {
      "type": "string",
      "format": "uri",
      "nullable": true,
      "description": "The URL of this resource."
     }
    }
   }
  }
 }
}
